name: My yaml

on:
  workflow_dispatch:
  schedule:
    #- cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: My snake job
         uses: Platane/snk/svg-only@v2

      - name: add, commit & push
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'Generate Contribution Snake' 
