name: My yaml
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # omiitable
jobs:
  build:
    name: My snake job
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif

        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./assets/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: main
          build_dir: ./assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
